### ISSUE TITLE
VueQuery exports

### ISSUE THREAD

**Issue by FedorSherbakov** [Shaddix/react-query-swagger#15]
It seems like `@tanstack/vue-query` exports are a bit different

`UseQueryResult` and `UseMutationResult` don't exist, but using `UseQueryReturnType` and `UseMutationReturnType` feels to solve issue

**Comment by Shaddix** [comment]
15.2.8 seems to fix this along with some other type errors (`vue-tsc --noEmit` is now run as part of pre release checking)

**Comment by FedorSherbakov** [comment]
Thanks!
