### ISSUE TITLE
JSON.Parse throw error, even if response is correct object

### ISSUE THREAD

**Issue by proggarapsody** [Shaddix/react-query-swagger#17]
```
SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at processLogin (Client.ts?ac1b:66:15)
    at eval (Client.ts?ac1b:48:10)
```

![изображение](https://user-images.githubusercontent.com/76034634/215677252-09f4c344-280f-4f1c-9361-b92421de64c9.png)
![изображение](https://user-images.githubusercontent.com/76034634/215678092-8fc8f53b-c9b9-424e-bafb-9daabf76c14b.png)
resultData200 value is 
```
{
    "data": {
        "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXNoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY3NTE0NTUxMSwiaXNzIjoiYWxmX2lkZW50aXR5IiwiYXVkIjoiYWxmX2FwcCJ9.rkxfEfO3g1iZgO4FBUXuhLXP8H9axOiq-CTlQexJHZc",
        "expirationAt": "2023-01-20T06:11:51.615097Z"
    },
    "errors": [],
    "status": 200
}
```
i don't understand why Json.parse can't parse this object, any thoughts?

**Comment by Shaddix** [comment]
the data you posted is indeed a valid JSON.

The thing is, `JSON.parse` expects a string as an argument.
But according to the error message, the first argument that you passed an already parsed `Object`, not a `string`.

So, somehow, `response.data` is already an object, while we expect a string. Maybe you are parsing the data via some interceptor?

Posting the full sample could help :)

**Comment by proggarapsody** [comment]
@Shaddix 
In this interceptor I didn't return config

```

client.interceptors.response.use(undefined, async (config) => {
  if (config?.response?.status === 401) {
    await refreshToken()
    client(config.request)
  }
return config
})

```

I close the issue
