### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by allocenx** [Shaddix/react-query-swagger#3]
This package is awesome. you have my gratitude, but is there an ETA for post/put/patch/delete mutations as well?

**Comment by Shaddix** [comment]
it's in the works now, hope that within a week there'd be an initial implementation to play with

**Comment by Shaddix** [comment]
initial support for mutations is pushed to npm
Though, it's barely tested now. We'll start to dogfood it next week to collect more information regarding bugs and issues.

Any feedback is very welcome!

**Comment by Shaddix** [comment]
I'm closing this one, since it's implemented, feel free to open new issues with some specific issues/concerns/feature requests regarding mutations
