### ISSUE TITLE
Duplicated functions

### ISSUE THREAD

**Issue by eladcandroid** [Shaddix/react-query-swagger#31]
I'm using
`npx react-query-swagger /tanstack /input:https://abc.com/WebApi/swagger/v1/swagger.json /output:src/api/axios-client.ts /template:Axios`

And I have duplicated functions with the same name:

For example - function alerts declared twice, one for the endpoint api/Reports/alerts and one for /api/Pipelines/Alerts...

What am I missing?

**Comment by Shaddix** [comment]
sorry for the delayed response, could you provide your swagger.json file so I could take a look?

Meanwhile, you could try adding `/operationGenerationMode:MultipleClientsFromFirstTagAndOperationId` to see if it helps (see [OperationGenerationMode](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs#L2) for other possible values)

**Comment by Shaddix** [comment]
I'm closing this, feel free to reopen with the details (e.g. with a swagger.json)
